version: '3.8'

services:
  fluent-client:
    image: dvladnik/fluentd-ui
    networks:
      - traefik-net
    volumes:
      - fluentd-conf:/root/.fluentd-ui
    deploy:
      labels:
        traefik.docker.network: "traefik-net"
        traefik.enable: "true"
        traefik.frontend.rule: "Host:fluent.j3dro.de,www.fluent.j3dro.de"
        traefik.port: 9292
    ports:
      - "127.0.0.1:24224:24224"

networks:
  traefik-net:
    external: true

volumes:
  fluentd-conf:
